import React, { useState } from 'react';
import { Search, FileText } from 'lucide-react';
import { CSVFile } from './types';

interface CsvExplorerProps {
  csvFiles: CSVFile[];
}

export default function CsvExplorer({ csvFiles }: CsvExplorerProps) {
  const [selectedCSVFile, setSelectedCSVFile] = useState<CSVFile>(csvFiles[0] || null);
  const [csvSearchQuery, setCsvSearchQuery] = useState<string>('');

  if (!selectedCSVFile) {
    return (
      <div className="bg-zinc-900/40 p-6 rounded-xl border border-zinc-800 text-center text-zinc-500 font-mono">
        No CSV databases available.
      </div>
    );
  }

  const filteredRows = selectedCSVFile.rows.filter(row => {
    if (!csvSearchQuery) return true;
    return Object.values(row).some(val => 
      String(val).toLowerCase().includes(csvSearchQuery.toLowerCase())
    );
  });

  return (
    <div className="flex flex-col gap-6 animate-fade-in">
      <div className="bg-zinc-900/60 rounded-xl p-5 border border-zinc-800">
        <h3 className="text-sm font-black tracking-widest text-zinc-300 uppercase">FLAT-FILE CSV REPORT DATABASE</h3>
        <p className="text-xs text-zinc-500">Inspect raw tabular reports generated by the background tracking routines in a standard SQL layout grid.</p>
      </div>

      {/* DUAL PANE CONTROL ENVIRONMENT */}
      <div className="grid grid-cols-1 xl:grid-cols-4 gap-6 items-start">
        
        {/* LEFT HAND CONTROL PANE: AVAILABLE CSV FILE DIRECTORY */}
        <div className="xl:col-span-1 bg-zinc-900/40 p-4 rounded-xl border border-zinc-800 flex flex-col gap-4">
          <span className="text-[10px] text-zinc-500 font-bold tracking-wider uppercase block border-b border-zinc-800 pb-2">
            System CSV Directory
          </span>

          <div className="flex flex-col gap-2">
            {csvFiles.map((file) => {
              const isActive = selectedCSVFile.name === file.name;
              return (
                <div
                  key={file.name}
                  onClick={() => {
                    setSelectedCSVFile(file);
                    setCsvSearchQuery('');
                  }}
                  className={`p-3 rounded-lg border cursor-pointer select-none transition-all ${
                    isActive 
                      ? 'bg-emerald-500/10 border-emerald-500 shadow-md shadow-emerald-500/5' 
                      : 'bg-zinc-950/40 border-zinc-850 hover:bg-zinc-900 hover:border-zinc-700'
                  }`}
                >
                  <div className="flex items-center gap-2.5">
                    <FileText className={`w-4 h-4 ${isActive ? 'text-emerald-400' : 'text-zinc-500'}`} />
                    <span className={`text-xs font-semibold ${isActive ? 'text-emerald-400' : 'text-zinc-300'}`}>
                      {file.name}
                    </span>
                  </div>
                  
                  <div className="mt-2.5 flex items-center justify-between text-[9px] text-zinc-500">
                    <span>{file.recordsCount} Records</span>
                    <span>{file.size}</span>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="mt-4 p-3 bg-zinc-950/60 rounded border border-zinc-850/60 text-[10px] text-zinc-500 leading-relaxed font-mono">
            💡 Clicking a ledger loads the parsed array directly into the database explorer table.
          </div>
        </div>

        {/* RIGHT HAND COLUMN: STRUCTURED SQL-LIKE GRID */}
        <div className="xl:col-span-3 bg-zinc-900/40 p-5 rounded-xl border border-zinc-800 flex flex-col gap-4">
          
          {/* Search & Statistics Filter Row */}
          <div className="flex flex-col md:flex-row items-center justify-between gap-4 border-b border-zinc-850 pb-4">
            <div className="flex items-center gap-3">
              <span className="text-xs bg-emerald-950/80 text-emerald-300 border border-emerald-800 px-2.5 py-1 rounded font-bold font-mono">
                SQL_VIEW
              </span>
              <div>
                <h4 className="text-xs font-bold text-zinc-300 font-mono">{selectedCSVFile.name}</h4>
                <p className="text-[10px] text-zinc-500">Last Synced: {selectedCSVFile.lastUpdated}</p>
              </div>
            </div>

            <div className="relative w-full md:w-64">
              <Search className="absolute left-3 top-2.5 w-3.5 h-3.5 text-zinc-500" />
              <input 
                type="text"
                placeholder="SQL Like Filter..."
                value={csvSearchQuery}
                onChange={(e) => setCsvSearchQuery(e.target.value)}
                className="bg-zinc-950 border border-zinc-850 text-zinc-300 text-xs rounded pl-9 pr-4 py-2 w-full outline-none focus:border-emerald-500 font-mono"
              />
            </div>
          </div>

          {/* Database Table Layout */}
          <div className="overflow-x-auto border border-zinc-850 rounded-lg">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-zinc-950 border-b border-zinc-855 text-[10px] text-zinc-400 tracking-wider">
                  {selectedCSVFile.headers.map((header) => (
                    <th key={header} className="p-3">{header}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-850 text-xs text-zinc-300 font-mono">
                {filteredRows.map((row, index) => (
                  <tr key={index} className="hover:bg-zinc-900/30 transition-all">
                    {selectedCSVFile.headers.map((header) => {
                      const cellValue = row[header];
                      let cellClass = "";
                      
                      if (header === 'Tracking_ID') cellClass = "text-emerald-400 font-bold";
                      if (header === 'Read_Number_Plate' || header === 'Plate_Consensus_String') cellClass = "font-black bg-zinc-950/40 border border-zinc-900 px-1.5 py-0.5 rounded";
                      if (header === 'Velocity_KMPH') cellClass = "text-yellow-500 font-semibold";
                      if (cellValue === 'CRITICAL' || cellValue === 'FAIL' || cellValue === 'NO') cellClass = "text-red-400 font-extrabold";
                      if (cellValue === 'PASS' || cellValue === 'YES') cellClass = "text-emerald-400 font-bold";
                      
                      return (
                        <td key={header} className={`p-3 border-r border-zinc-850/40 last:border-0 ${cellClass}`}>
                          {String(cellValue)}
                        </td>
                      );
                    })}
                  </tr>
                ))}
                {filteredRows.length === 0 && (
                  <tr>
                    <td colSpan={selectedCSVFile.headers.length} className="p-8 text-center text-zinc-500">
                      No records detected matching database specifications.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="flex items-center justify-between text-[10px] text-zinc-500 pt-2 font-mono">
            <span>Showing {filteredRows.length} rows inside compiled flat storage matrix</span>
            <span>Database Protocol: ANSI Format</span>
          </div>

        </div>

      </div>

    </div>
  );
}
